create table "public"."youtube_videos" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "video_code" text not null,
    "title" text,
    "description" text,
    "answer" text
);


CREATE UNIQUE INDEX youtube_videos_pkey ON public.youtube_videos USING btree (id);

alter table "public"."youtube_videos" add constraint "youtube_videos_pkey" PRIMARY KEY using index "youtube_videos_pkey";