create table "public"."youtube_vidoes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "video_code" text not null,
    "title" text,
    "description" text,
    "answer" text
);


CREATE UNIQUE INDEX youtube_vidoes_pkey ON public.youtube_vidoes USING btree (id);

alter table "public"."youtube_vidoes" add constraint "youtube_vidoes_pkey" PRIMARY KEY using index "youtube_vidoes_pkey";